# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FinnaCli < Formula
  desc "CLI for finna-app cloud cost management"
  homepage "https://github.com/acarmisc/finna-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/acarmisc/finna-cli/releases/download/v0.1.1/finna_0.1.1_darwin_amd64.tar.gz"
      sha256 "3acaa6b965c1181cc7c642eaf5a90b13b4101aab9bfcf64af33f11da6d218da9"

      define_method(:install) do
        bin.install "finna"
        generate_completions_from_executable(bin/"finna", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/acarmisc/finna-cli/releases/download/v0.1.1/finna_0.1.1_darwin_arm64.tar.gz"
      sha256 "7143d70f57966615754a9669a618815000958e3b60a647733dd0f64998fcabf2"

      define_method(:install) do
        bin.install "finna"
        generate_completions_from_executable(bin/"finna", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/acarmisc/finna-cli/releases/download/v0.1.1/finna_0.1.1_linux_amd64.tar.gz"
      sha256 "a8607536f1ba37929f5b5ee029850783b10138befc7d287ba7e2728ddf889080"
      define_method(:install) do
        bin.install "finna"
        generate_completions_from_executable(bin/"finna", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/acarmisc/finna-cli/releases/download/v0.1.1/finna_0.1.1_linux_arm64.tar.gz"
      sha256 "5abbef980b630beff9602bda7e4585976f755f5dbd5dda760683e973b658d8c0"
      define_method(:install) do
        bin.install "finna"
        generate_completions_from_executable(bin/"finna", "completion")
      end
    end
  end

  test do
    system "#{bin}/finna", "version"
  end
end
