# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FinnaCli < Formula
  desc "CLI for finna-app cloud cost management"
  homepage "https://github.com/acarmisc/finna-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/acarmisc/finna-cli/releases/download/v0.1.0/finna_0.1.0_darwin_amd64.tar.gz"
      sha256 "91175a946dd21ac128e9f027c37766509b3d5a1fc21b5444d90fc0c27b514525"

      define_method(:install) do
        bin.install "finna"
        generate_completions_from_executable(bin/"finna", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/acarmisc/finna-cli/releases/download/v0.1.0/finna_0.1.0_darwin_arm64.tar.gz"
      sha256 "d0170cd8d476f8836517ed92039d4ea683ed660f29a33b9044c28b9084723cd5"

      define_method(:install) do
        bin.install "finna"
        generate_completions_from_executable(bin/"finna", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/acarmisc/finna-cli/releases/download/v0.1.0/finna_0.1.0_linux_amd64.tar.gz"
      sha256 "78ddaa0d2b349457d562f890aabec5dcec5b18588f49e3e38acb780bf61a3aa4"
      define_method(:install) do
        bin.install "finna"
        generate_completions_from_executable(bin/"finna", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/acarmisc/finna-cli/releases/download/v0.1.0/finna_0.1.0_linux_arm64.tar.gz"
      sha256 "58fb6da1ee7b1fada1ee8a3f25b78e8f430e3a8bd188efc9952bd9ffa2faab0e"
      define_method(:install) do
        bin.install "finna"
        generate_completions_from_executable(bin/"finna", "completion")
      end
    end
  end

  test do
    system "#{bin}/finna", "version"
  end
end
